name: DesignKorps
favicon: null
layout_spectrum: 0.2733
typography_spectrum: 0.50343
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00131a'
    - '#879fa9'
    - '#427c90'
    - '#29363a'
    - '#e2e4e5'
  brandStrength: 0.23460307228378952
  lightness: 0.9002835012506694
  saturation: 0.9065715507604182
  rhythmicContrast: 0.7126138058956712
purpose: []
