name: DesignKorps
favicon: null
layout_spectrum: 0.6283275079913437
typography_spectrum: 0.9719489007256925
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.23460307228378952
  lightness: 0.9002835012506694
  saturation: 0.9065715507604182
  rhythmicContrast: 0.7126138058956712
purpose: []
