name: DesignKorps
favicon: null
layout_spectrum: 0.80227
typography_spectrum: 0.48309
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040203'
    - '#fdfdfd'
    - '#4d2d18'
    - '#e8ab74'
    - '#0374b7'
  brandStrength: 0.375
  lightness: 0.9002835012506694
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
