name: DesignKorps
favicon: null
layout_spectrum: 0.7519
typography_spectrum: 0.48309
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1a1114'
    - '#9a7d82'
    - '#b6a786'
    - '#8e8d79'
  brandStrength: 0.0625
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
