name: DesignKorps
favicon: null
layout_spectrum: 0.9786
typography_spectrum: 0.48309
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#233460'
    - '#2d65b0'
    - '#7e7194'
    - '#bdb6c9'
  brandStrength: 0.375
  lightness: 0.9375
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
