name: DesignKorps
favicon: null
layout_spectrum: 0.92304
typography_spectrum: 0.63926
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000103'
    - '#fbfcfe'
    - '#1d90ce'
    - '#073059'
    - '#71c0eb'
  brandStrength: 0.75
  lightness: 0.9002835012506694
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
